-- Create Users table
CREATE TABLE IF NOT EXISTS Users (
    Id SERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create ChatRooms table
CREATE TABLE IF NOT EXISTS ChatRooms (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Type VARCHAR(20) NOT NULL, -- 'Private', 'Group'
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create RoomParticipants table (Many-to-Many relationship)
CREATE TABLE IF NOT EXISTS RoomParticipants (
    RoomId INTEGER NOT NULL,
    UserId INTEGER NOT NULL,
    JoinedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    LastReadAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RoomId, UserId),
    FOREIGN KEY (RoomId) REFERENCES ChatRooms(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

-- Create Messages table
CREATE TABLE IF NOT EXISTS Messages (
    Id SERIAL PRIMARY KEY,
    RoomId INTEGER NOT NULL,
    SenderId INTEGER NOT NULL,
    Content TEXT NOT NULL,
    SentAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    IsRead BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (RoomId) REFERENCES ChatRooms(Id) ON DELETE CASCADE,
    FOREIGN KEY (SenderId) REFERENCES Users(Id) ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_messages_roomid ON Messages(RoomId);
CREATE INDEX IF NOT EXISTS idx_messages_sentat ON Messages(SentAt);
